#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

#
# SYSTEM PACKAGES
#
apt-get update
xargs apt-get install -y --force-yes < /build/packages.txt
apt-get clean

#
# SUPPORTED BUILDPACKS
#
mkdir -p /build/buildpacks
cd /build/buildpacks
xargs -L 1 git clone --depth=1 < /build/buildpacks.txt

#
# MISC
#

# Ruby buildpack system configuration
gem install bundler
